# Generated by Django 3.1.5 on 2021-05-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vilon', '0003_auto_20210521_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtain',
            name='type',
            field=models.CharField(choices=[('tefira', 'תפירה'), ('zebra', 'זברה')], default='FRESHMAN', max_length=30),
        ),
    ]
